# Đăng ký tài khoản
POST http://localhost:8081/api/auth/register
Content-Type: application/json

{
  "maNhanVien": "NV00004",
  "matKhau": "123"
}

###

# Đăng nhập
POST http://localhost:8081/api/auth/login
Content-Type: application/json

{
  "maNhanVien": "NV0001",
  "matKhau": "123"
}

###

# Đổi mật khẩu
POST http://localhost:8081/api/auth/change-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYU5oYW5WaWVuIjoiTlYwMDAxIiwicGhhblF1eWVuIjoxLCJpYXQiOjE3Mjg2MjI0MjYsImV4cCI6MTcyODYyNjAyNn0.6w7UGUDk17jQc2Jz9plu71kGj_eqSd4fB_2sS2rYgbg
Content-Type: application/json

{
  "maNhanVien": "NV001",
  "oldPassword": "123456",
  "newPassword": "654321"
}

###

# Đổi quyền tài khoản
POST http://localhost:8081/api/auth/change-role
Authorization: Bearer <JWT_TOKEN>
Content-Type: application/json

{
  "maNhanVien": "NV001",
  "phanQuyen": 1
}

###

# Lấy danh sách ca học
GET http://localhost:8081/api/cahoc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYU5oYW5WaWVuIjoiTlYwMDAxIiwicGhhblF1eWVuIjozLCJpYXQiOjE3MjkzMzE1MDQsImV4cCI6MTcyOTMzNTEwNH0.yrHsaH8Ahgl9uIDWn1rcZMCUY1L6txB5uuYKKdxfCOA

###

# Thêm ca học
POST http://localhost:8081/api/cahoc/them-cahoc
Authorization: Bearer <JWT_TOKEN>
Content-Type: application/json

{
  "batDau": "2024-10-05T08:00:00",
  "ketThuc": "2024-10-05T10:00:00",
  "ghiChu": "Ca sáng"
}

###

# Cập nhật ca học
POST http://localhost:8081/api/cahoc/sua-cahoc
Authorization: Bearer <JWT_TOKEN>
Content-Type: application/json

{
  "maCa": "CA001",
  "batDau": "2024-10-06T08:00:00",
  "ketThuc": "2024-10-06T10:00:00",
  "ghiChu": "Ca sáng sửa"
}

###

# Lấy danh sách hóa đơn
GET http://localhost:8081/api/hoadon/ds-hoadon
Authorization: Bearer <JWT_TOKEN>

###

# Thêm hóa đơn
POST http://localhost:8081/api/hoadon/them-hoadon
Authorization: Bearer <JWT_TOKEN>
Content-Type: application/json

{
  "maNhanVien": "NV001",
  "maHocVien": "HV001",
  "ngayTaoHoaDon": "2024-10-05T08:00:00",
  "trangThai": "Đã thanh toán",
  "ghiChu": "Hóa đơn học phí"
}

###

# Lấy danh sách học viên
GET http://localhost:8081/api/hocvien/ds-hocvien
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYU5oYW5WaWVuIjoiTlYwMDAxIiwicGhhblF1eWVuIjoxLCJpYXQiOjE3Mjg0NzEwNzIsImV4cCI6MTcyODQ3NDY3Mn0.M2_mlM4f99_gtaRNVpStuEFSHfsqsht0rNb9x4XH6WI

###

# Thêm học viên
POST http://localhost:8081/api/hocvien/them-hocvien
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYU5oYW5WaWVuIjoiTlYwMDAxIiwicGhhblF1eWVuIjoxLCJpYXQiOjE3Mjk0MDE2MDMsImV4cCI6MTcyOTQwNTIwM30.CkDMVsqqGUFbHqhNEnSYkcL9prmd9XmJuCFnvMhMT24
Content-Type: application/json

{
  "hocViens": [
    {
      "tenHocVien": "Nguyen Van B",
      "ngaySinh": "2000-01-01",
      "gioiTinh": "Nam",
      "sdt": "0901234567",
      "email": "nguyenvana@example.com"
    }
  ]
}

###

# Cập nhật học viên
POST http://localhost:8081/api/hocvien/sua-hocvien
Authorization: Bearer <JWT_TOKEN>
Content-Type: application/json

{
  "maHocVien": "HV001",
  "tenHocVien": "Nguyen Van B",
  "ngaySinh": "2000-01-01",
  "gioiTinh": "Nam",
  "sdt": "0909876543",
  "email": "nguyenvanb@example.com"
}

###

# Lấy danh sách lớp học
GET http://localhost:8081/api/lophoc/ds-lophoc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYU5oYW5WaWVuIjoiTlYwMDAxIiwicGhhblF1eWVuIjoxLCJpYXQiOjE3Mjk0MTEwOTgsImV4cCI6MTcyOTQxNDY5OH0.HsIg7_Z9Wrh0KmyPOts_suJYFMC285Lgu_Pe7LnrZs8

###

# Thêm lớp học
POST http://localhost:8081/api/lophoc/them-lophoc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYU5oYW5WaWVuIjoiTlYwMDAxIiwicGhhblF1eWVuIjoxLCJpYXQiOjE3MjgxMjAwMDYsImV4cCI6MTcyODEyMzYwNn0.sWdhoh0TN_iEphyYWMbZJx6J1liprIn4tVEhuLaabKg
Content-Type: application/json

{
  "lopHocs": [
    {
      "tenLopHoc": "Lop Toan 2",
      "maMonHoc": "MH0001",
      "maNhanVien": "NV0001",
      "ngayBatDau": "2024-10-10",
      "soLuong": 30,
      "ghiChu": "Lớp học toán"
    }
  ]
}

###

# Cập nhật lớp học
POST http://localhost:8081/api/lophoc/sua-lophoc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYU5oYW5WaWVuIjoiTlYwMDAxIiwicGhhblF1eWVuIjoxLCJpYXQiOjE3MjgxMjAwMDYsImV4cCI6MTcyODEyMzYwNn0.sWdhoh0TN_iEphyYWMbZJx6J1liprIn4tVEhuLaabKg
Content-Type: application/json

{
  "maLopHoc": "LH0002",
  "tenLopHoc": "Lop Tieng Anh 2",
  "maMonHoc": "MH0001",
  "maNhanVien": "NV0001",
  "ngayBatDau": "2024-11-01",
  "soLuong": 25,
  "trangThai": "Đã mở đăng ký",
  "ghiChu": "Lớp trung cấp"
}

###

# Lấy danh sách môn học
GET http://localhost:8081/api/monhoc/ds-monhoc
Authorization: Bearer <JWT_TOKEN>

###

# Thêm môn học
POST http://localhost:8081/api/monhoc/them-monhoc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYU5oYW5WaWVuIjoiTlYwMDAxIiwicGhhblF1eWVuIjoxLCJpYXQiOjE3Mjk5Mzg5MzEsImV4cCI6MTcyOTk0MjUzMX0.1XihSl0DCTdRrNgj7llh0nEI42wZpUPW0agBoQpg0pY
Content-Type: application/json

{
  "tenMonHoc": "Ts8",
  "soBuoiHoc": 20,
  "hocPhi": 500000,
  "moTa": "Môn toán căn bản"
}

###

# Cập nhật môn học
PUT http://localhost:8081/api/monhoc/sua-monhoc
Authorization: Bearer <JWT_TOKEN>
Content-Type: application/json

{
  "maMonHoc": "MH001 abc",
  "tenMonHoc": "Vật lý",
  "soBuoiHoc": 30,
  "hocPhi": 600000,
  "moTa": "Môn vật lý nâng cao"
}

###

# Lấy danh sách nhân viên
GET http://localhost:8081/api/nhanvien/ds-nhanvien
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYU5oYW5WaWVuIjoiTlYwMDAxIiwicGhhblF1eWVuIjoxLCJpYXQiOjE3Mjg0NzEwNzIsImV4cCI6MTcyODQ3NDY3Mn0.M2_mlM4f99_gtaRNVpStuEFSHfsqsht0rNb9x4XH6WI

###

# Thêm nhân viên
POST http://localhost:8081/api/nhanvien/them-nhanvien
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYU5oYW5WaWVuIjoiTlYwMDAxIiwicGhhblF1eWVuIjoxLCJpYXQiOjE3Mjk0MDE2MDMsImV4cCI6MTcyOTQwNTIwM30.CkDMVsqqGUFbHqhNEnSYkcL9prmd9XmJuCFnvMhMT24
Content-Type: application/json

{
  "nhanViens": [
    {
      "tenNhanVien": "Le Thi B",
      "chucVu": "Giảng viên",
      "ngayVaoLam": "2024-01-01",
      "gioiTinh": "Nữ",
      "sdt": "0909876543",
      "email": "lethib@example.com"
    }
  ]
}

###

# Cập nhật nhân viên
POST http://localhost:8081/api/nhanvien/sua-nhanvien
Authorization: Bearer <JWT_TOKEN>
Content-Type: application/json

{
  "maNhanVien": "NV001",
  "tenNhanVien": "Le Van C",
  "chucVu": "Trưởng phòng",
  "ngayVaoLam": "2023-12-01",
  "gioiTinh": "Nam",
  "sdt": "0906543210",
  "email": "levanc@example.com"
}

###

# Lấy danh sách phòng học
GET http://localhost:8081/api/phonghoc/ds-phong
Authorization: Bearer <JWT_TOKEN>

###

# Thêm phòng học
POST http://localhost:8081/api/phonghoc/them-phong
Authorization: Bearer <JWT_TOKEN>
Content-Type: application/json

{
  "soLuong": 50,
  "trangThai": "Đang hoạt động",
  "ghiChu": "Phòng lớn"
}

###

# Cập nhật phòng học
POST http://localhost:8081/api/phonghoc/sua-phong
Authorization: Bearer <JWT_TOKEN>
Content-Type: application/json

{
  "maPhong": "PH001",
  "soLuong": 60,
  "trangThai": "Đang bảo trì",
  "ghiChu": "Phòng lớn sửa chữa"
}

###

# Lấy danh sách tài khoản
GET http://localhost:8081/api/auth/ds-taikhoan
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYU5oYW5WaWVuIjoiTlYwMDAxIiwicGhhblF1eWVuIjoxLCJpYXQiOjE3Mjg0NzEwNzIsImV4cCI6MTcyODQ3NDY3Mn0.M2_mlM4f99_gtaRNVpStuEFSHfsqsht0rNb9x4XH6WI

### Cập nhập trạng thái tài khoản
POST http://localhost:8081/api/auth/update-trangthai
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYU5oYW5WaWVuIjoiTlYwMDAxIiwicGhhblF1eWVuIjoxLCJpYXQiOjE3Mjg2MjI3MDksImV4cCI6MTcyODYyNjMwOX0.YShtWj1inojPxtAPmorLj-T0LfpjE4tE_gyzaNynGtQ
Content-Type: application/json

{
    "maNhanVien": "NV0002",
    "trangThai": "Đã khóa"
}

### Khóa tài khoản
POST http://localhost:8081/api/auth/khoa-taikhoan
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYU5oYW5WaWVuIjoiTlYwMDAxIiwicGhhblF1eWVuIjoxLCJpYXQiOjE3MjkxNTE0NzksImV4cCI6MTcyOTE1NTA3OX0.gAyY8ZmYwtVOpstHGDUVE7_N07ur4C8gY1ctebEV0hY
Content-Type: application/json

{
  "maNhanVien": "NV0002"
}

### Mở khóa tài khoản
POST http://localhost:8081/api/auth/moKhoa-taiKhoan
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYU5oYW5WaWVuIjoiTlYwMDAxIiwicGhhblF1eWVuIjoxLCJpYXQiOjE3MjkxNTE0NzksImV4cCI6MTcyOTE1NTA3OX0.gAyY8ZmYwtVOpstHGDUVE7_N07ur4C8gY1ctebEV0hY
Content-Type: application/json

{
  "maNhanVien": "NV0002"
}

### Lấy ds học viên theo lớp
Get http://localhost:8081/api/lophoc/ds-hocvien
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYU5oYW5WaWVuIjoiTlYwMDAxIiwicGhhblF1eWVuIjoxLCJpYXQiOjE3Mjk2MDk3ODcsImV4cCI6MTcyOTYxMzM4N30.ZyfUe6et7DfgN7G1bjRG9RYtKIptR0QI3W2NmUXlY3M
Content-Type: application/json

### Lấy ds học viên trong lớp theo mã lớp
Get http://localhost:8081/api/lophoc/ds-hocvien02
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYU5oYW5WaWVuIjoiTlYwMDAxIiwicGhhblF1eWVuIjoxLCJpYXQiOjE3Mjk2MDk3ODcsImV4cCI6MTcyOTYxMzM4N30.ZyfUe6et7DfgN7G1bjRG9RYtKIptR0QI3W2NmUXlY3M

{
  "maLopHoc": "LH0001"
}

### Xóa phòng học
POST http://localhost:8081/api/phonghoc/xoa-phong
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYU5oYW5WaWVuIjoiTlYwMDAxIiwicGhhblF1eWVuIjoxLCJpYXQiOjE3Mjk0MDA0NzIsImV4cCI6MTcyOTQwNDA3Mn0.-UMrs3ia0DnKQcv4MmGOOuJFl9q_kBl8ea4qiOLpMzs
Content-Type: application/json

{
  "maPhong": "P0004"
}

### Xóa ca học
POST http://localhost:8081/api/cahoc/xoa-cahoc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYU5oYW5WaWVuIjoiTlYwMDAxIiwicGhhblF1eWVuIjoxLCJpYXQiOjE3Mjk0MDA0NzIsImV4cCI6MTcyOTQwNDA3Mn0.-UMrs3ia0DnKQcv4MmGOOuJFl9q_kBl8ea4qiOLpMzs
Content-Type: application/json

{
  "maCa": "Ca0005"
}

### Xóa môn học
POST http://localhost:8081/api/monhoc/xoa-monhoc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYU5oYW5WaWVuIjoiTlYwMDAxIiwicGhhblF1eWVuIjoxLCJpYXQiOjE3Mjk5Mzg5MzEsImV4cCI6MTcyOTk0MjUzMX0.1XihSl0DCTdRrNgj7llh0nEI42wZpUPW0agBoQpg0pY
Content-Type: application/json

{
  "maMonHoc": "MH0019"
}


### Xóa nhân viên. Xóa nhân viên sẽ Xóa luôn tài khoản
POST http://localhost:8081/api/nhanvien/xoa-nhanvien
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYU5oYW5WaWVuIjoiTlYwMDAxIiwicGhhblF1eWVuIjoxLCJpYXQiOjE3Mjk0MDA0NzIsImV4cCI6MTcyOTQwNDA3Mn0.-UMrs3ia0DnKQcv4MmGOOuJFl9q_kBl8ea4qiOLpMzs
Content-Type: application/json

{
  "maNhanVien": "NV00004"
}

### Xóa học viên
POST http://localhost:8081/api/hocvien/xoa-hocvien
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYU5oYW5WaWVuIjoiTlYwMDAxIiwicGhhblF1eWVuIjoxLCJpYXQiOjE3Mjk0MDA0NzIsImV4cCI6MTcyOTQwNDA3Mn0.-UMrs3ia0DnKQcv4MmGOOuJFl9q_kBl8ea4qiOLpMzs
Content-Type: application/json

{
  "maHocVien": "HV0005"
}

### Xóa lớp học
POST http://localhost:8081/api/lophoc/xoa-lophoc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYU5oYW5WaWVuIjoiTlYwMDAxIiwicGhhblF1eWVuIjoxLCJpYXQiOjE3Mjk0MDA0NzIsImV4cCI6MTcyOTQwNDA3Mn0.-UMrs3ia0DnKQcv4MmGOOuJFl9q_kBl8ea4qiOLpMzs
Content-Type: application/json

{
  "maLopHoc": "LH0001"
}

### xuat xlsx
GET http://localhost:8081/api/nhanvien/export-nhanvien
Authorization: Bearer